# I don't know what the minimum size is, but we cannot build on t3.micro.

# TODO: Factor common builds between different tests.

# The parameters for our job matrix:
#
# 1. Generator (Make, Ninja, MSBuild)
# 2. Compiler (GCC, Clang, MSVC)
# 3. Build type (Debug, Release)
# 4. Definitions (-Dunity=OFF, -Dassert=ON, ...)


.job_linux_build_test:
  stage: build
  tags:
    - jfreeman
    - linux
    - c5.2xlarge
  image: thejohnfreeman/rippled-build-ubuntu:develop
  script:
    - bin/ci/build.sh
    - bin/ci/test.sh
  cache:
    # Generate a new UUID whenever you want to bust the cache, e.g. when the
    # dependency versions have been bumped.
    key: 910f11a6-8869-4ee4-9681-905f21b14b0c
    # By default, jobs pull the cache. Only a few specially chosen jobs update
    # the cache (with policy `pull-push`); one for each unique combination of
    # (generator, compiler, build type).
    policy: pull
    paths:
      - .nih_c/

'build+test Make GCC Debug':
  extends: .job_linux_build_test
  variables:
    GENERATOR: Unix Makefiles
    COMPILER: gcc
    BUILD_TYPE: Debug
  cache:
    policy: pull-push

'build+test Ninja GCC Debug':
  extends: .job_linux_build_test
  variables:
    GENERATOR: Ninja
    COMPILER: gcc
    BUILD_TYPE: Debug
  cache:
    policy: pull-push

'build+test Ninja GCC Debug -Dstatic=OFF':
  extends: .job_linux_build_test
  variables:
    GENERATOR: Ninja
    COMPILER: gcc
    BUILD_TYPE: Debug
    CMAKE_ARGS: '-Dstatic=OFF'

'build+test Ninja GCC Debug -Dstatic=OFF -DBUILD_SHARED_LIBS=ON':
  extends: .job_linux_build_test
  variables:
    GENERATOR: Ninja
    COMPILER: gcc
    BUILD_TYPE: Debug
    CMAKE_ARGS: '-Dstatic=OFF -DBUILD_SHARED_LIBS=ON'

'build+test Ninja GCC Debug -Dunity=OFF':
  extends: .job_linux_build_test
  variables:
    GENERATOR: Ninja
    COMPILER: gcc
    BUILD_TYPE: Debug
    CMAKE_ARGS: '-Dunity=OFF'

'build+test Ninja GCC Release -Dassert=ON':
  extends: .job_linux_build_test
  variables:
    GENERATOR: Ninja
    COMPILER: gcc
    BUILD_TYPE: Release
    CMAKE_ARGS: '-Dassert=ON'
  cache:
    policy: pull-push

'build+test(manual) Ninja GCC Release -Dassert=ON':
  extends: .job_linux_build_test
  variables:
    GENERATOR: Ninja
    COMPILER: gcc
    BUILD_TYPE: Release
    CMAKE_ARGS: '-Dassert=ON'
    MANUAL_TEST: 'true'

'build+test Make clang Debug':
  extends: .job_linux_build_test
  variables:
    GENERATOR: Unix Makefiles
    COMPILER: clang
    BUILD_TYPE: Debug
  cache:
    policy: pull-push

'build+test Ninja clang Debug':
  extends: .job_linux_build_test
  variables:
    GENERATOR: Ninja
    COMPILER: clang
    BUILD_TYPE: Debug
  cache:
    policy: pull-push

'build+test Ninja clang Debug -Dunity=OFF':
  extends: .job_linux_build_test
  variables:
    GENERATOR: Ninja
    COMPILER: clang
    BUILD_TYPE: Debug
    CMAKE_ARGS: '-Dunity=OFF'

'build+test Ninja clang Debug -Dunity=OFF -Dsan=address':
  extends: .job_linux_build_test
  variables:
    GENERATOR: Ninja
    COMPILER: clang
    BUILD_TYPE: Debug
    CMAKE_ARGS: '-Dunity=OFF -Dsan=address'
    CONCURRENT_TESTS: 1

'build+test Ninja clang Debug -Dunity=OFF -Dsan=undefined':
  extends: .job_linux_build_test
  variables:
    GENERATOR: Ninja
    COMPILER: clang
    BUILD_TYPE: Debug
    CMAKE_ARGS: '-Dunity=OFF -Dsan=undefined'

'build+test Ninja clang Release -Dassert=ON':
  extends: .job_linux_build_test
  variables:
    GENERATOR: Ninja
    COMPILER: clang
    BUILD_TYPE: Release
    CMAKE_ARGS: '-Dassert=ON'
  cache:
    policy: pull-push
