[package]
name = "CFTokenIssuanceCreate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plugin-transactor = { path = "../../plugin-transactor" }
rippled-bridge = { path = "../../rippled-bridge" }
xrpl-rust-sdk-core = {path = "../../../../../../../github/xpring-eng/xrpl-rust-sdk/xrpl-rust-sdk-core"}
cxx = "1.0.94"
libc = "0.2.142"
once_cell = "1.17.1"
hex = "0.4.3"