name: Trigger rippled-packages repository
on: [pull_request, push]
jobs:
  dispatch_build_event:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Send build_packages repository_dispatch event to rippled-packages
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          curl -H "Authorization: token $GITHUB_TOKEN" \
              -H 'Accept: application/vnd.github.v3+json' \
              "https://api.github.com/repos/legleux/rippled-packages/dispatches" \
              -d '{"event_type": "build_packages", "client_payload": {"SHA": "${{ github.sha }}"}}'